### ISSUE TITLE
Lucene++ test segfault.

### ISSUE THREAD

**Issue by LocutusOfBorg** [luceneplusplus/LucenePlusPlus#87]
Hi, running the tester makes the program segfault after a while...

OS: ubuntu 14.10
ARCH: amd64 

```
./src/test/lucene++-tester

[...]
[----------] 4 tests from Base64Test
[ RUN      ] Base64Test.testEncodeSmall
[       OK ] Base64Test.testEncodeSmall (0 ms)
[ RUN      ] Base64Test.testEncodeLarge
[       OK ] Base64Test.testEncodeLarge (0 ms)
[ RUN      ] Base64Test.testDecodeSmall
[       OK ] Base64Test.testDecodeSmall (0 ms)
[ RUN      ] Base64Test.testDecodeLaarge
[       OK ] Base64Test.testDecodeLaarge (0 ms)
[----------] 4 tests from Base64Test (1 ms total)

[----------] Global test environment tear-down
[==========] 1472 tests from 201 test cases ran. (379808 ms total)
[  PASSED  ] 1472 tests.
Segmentation fault
```

**Comment by LocutusOfBorg** [comment]
#1  0x00007ffff64292be in std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_M_clone(std::allocator<wchar_t> const&, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff6429a8c in std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000000000ee13ec in Lucene::getTempDir () at /home/locutus/branches/lucene++/src/test/util/TestUtils.cpp:42
#4  0x0000000000f05150 in Lucene::LuceneGlobalFixture::~LuceneGlobalFixture (this=<optimized out>, __in_chrg=<optimized out>) at /home/locutus/branches/lucene++/src/test/util/LuceneGlobalFixture.cpp:22
#5  0x0000000000f051f9 in Lucene::LuceneGlobalFixture::~LuceneGlobalFixture (this=0x15a79e0, __in_chrg=<optimized out>) at /home/locutus/branches/lucene++/src/test/util/LuceneGlobalFixture.cpp:24
#6  0x0000000000f16638 in Delete<testing::Environment> (x=<optimized out>) at /home/locutus/branches/lucene++/src/test/gtest/src/gtest-internal-inl.h:340
#7  for_each<__gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*> >, void (*)(testing::Environment*)> (__f=<optimized out>, __last=..., __first=)
    at /usr/include/c++/4.9/bits/stl_algo.h:3756
#8  ForEach<std::vector<testing::Environment*>, void (*)(testing::Environment*)> (functor=<optimized out>, c=std::vector of length 1, capacity 1 = {...})
    at /home/locutus/branches/lucene++/src/test/gtest/src/gtest-internal-inl.h:296
#9  testing::internal::UnitTestImpl::~UnitTestImpl (this=0x150d550, __in_chrg=<optimized out>) at /home/locutus/branches/lucene++/src/test/gtest/src/gtest.cc:4029
#10 0x0000000000f16a72 in ~UnitTestImpl (this=0x150d550, __in_chrg=<optimized out>) at /home/locutus/branches/lucene++/src/test/gtest/src/gtest.cc:4032
#11 testing::UnitTest::~UnitTest (this=0x1504d80 <testing::UnitTest::GetInstance()::instance>, __in_chrg=<optimized out>) at /home/locutus/branches/lucene++/src/test/gtest/src/gtest.cc:3972
#12 0x00007ffff5ab3d32 in __run_exit_handlers (status=0, listp=0x7ffff5e3e698 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#13 0x00007ffff5ab3d85 in __GI_exit (status=<optimized out>) at exit.c:104
#14 0x00007ffff5a9aa47 in __libc_start_main (main=0x826110 <main(int, char**)>, argc=1, argv=0x7fffffffe3d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe3c8)
    at libc-start.c:323
#15 0x0000000000838b49 in _start ()
