### ISSUE TITLE
test failures in i386 architectures

### ISSUE THREAD

**Issue by LocutusOfBorg** [luceneplusplus/LucenePlusPlus#98]
Hi, this is the snip of the log, let me know if you need something more

[       OK ] BooleanMinShouldMatchTest.testRandomQueries (131379 ms)
[----------] 15 tests from BooleanMinShouldMatchTest (131986 ms total)

[----------] 11 tests from Boolean2Test
[ RUN      ] Boolean2Test.testQueries01
lucene++-tester: /build/lucene++-kbR2iw/lucene++-3.0.7/include/Array.h:103: TYPE& Lucene::Array<TYPE>::operator[](int32_t) const [with TYPE = unsigned char; int32_t = int]: Assertion `i >= 0 && i < array->size' failed.

the full build log is located there
https://buildd.debian.org/status/fetch.php?pkg=lucene%2B%2B&arch=i386&ver=3.0.7-4&stamp=1437151295

**Comment by LocutusOfBorg** [comment]
Here the backtrace
#0  0xf6ff9ddc in raise () from /lib/i386-linux-gnu/libc.so.6
#1  0xf6ffb463 in abort () from /lib/i386-linux-gnu/libc.so.6
#2  0xf6ff30f6 in ?? () from /lib/i386-linux-gnu/libc.so.6
#3  0xf6ff31a7 in __assert_fail () from /lib/i386-linux-gnu/libc.so.6
#4  0xf78ae39f in operator[] (this=0xa60cb7c, i=<optimized out>) at /lucene++-3.0.7/include/Array.h:103
#5  Lucene::SkipBuffer::readByte (this=0xa60cb5c) at /lucene++-3.0.7/src/core/index/MultiLevelSkipListReader.cpp:202
#6  0xf7922f41 in Lucene::IndexInput::readVInt (this=0xa60cb5c) at /lucene++-3.0.7/src/core/store/IndexInput.cpp:36
#7  0xf77c3ee5 in Lucene::DefaultSkipListReader::readSkipData (this=0x9993e14, level=1, skipStream=...) at /lucene++-3.0.7/src/core/index/DefaultSkipListReader.cpp:80
#8  0xf78ae415 in Lucene::MultiLevelSkipListReader::loadNextSkip (this=0x9993e14, level=1) at /lucene++-3.0.7/src/core/index/MultiLevelSkipListReader.cpp:97
#9  0xf78aeaa1 in Lucene::MultiLevelSkipListReader::skipTo (this=0x9993e14, target=4095) at /lucene++-3.0.7/src/core/index/MultiLevelSkipListReader.cpp:66
#10 0xf776e0db in Lucene::SegmentTermDocs::skipTo (this=0x9993b34, target=4095) at /lucene++-3.0.7/src/core/index/SegmentTermDocs.cpp:197
#11 0xf75ad8b6 in Lucene::TermScorer::advance (this=0x945c024, target=4095) at /lucene++-3.0.7/src/core/search/TermScorer.cpp:104
#12 0xf7662996 in Lucene::ConjunctionScorer::doNext (this=0x9990e2c) at /lucene++-3.0.7/src/core/search/ConjunctionScorer.cpp:72
#13 0xf7662c74 in Lucene::ConjunctionScorer::nextDoc (this=0x9990e2c) at /lucene++-3.0.7/src/core/search/ConjunctionScorer.cpp:100
#14 0xf75a36c6 in Lucene::BooleanScorer2::score (this=0x945d7d4, collector=...) at /lucene++-3.0.7/src/core/search/BooleanScorer2.cpp:97
#15 0xf7665e1f in Lucene::IndexSearcher::search (this=0x952b6a4, weight=..., filter=..., results=...) at /lucene++-3.0.7/src/core/search/IndexSearcher.cpp:114
#16 0xf7665fb5 in Lucene::IndexSearcher::search (this=0x952b6a4, weight=..., filter=..., n=1) at /lucene++-3.0.7/src/core/search/IndexSearcher.cpp:94
#17 0xf75b0060 in Lucene::Searcher::search (this=0x952b6a4, query=..., filter=..., n=1) at /lucene++-3.0.7/src/core/search/Searcher.cpp:35
#18 0xf75b0477 in Lucene::Searcher::search (this=0x952b6a4, query=..., n=1) at /lucene++-3.0.7/src/core/search/Searcher.cpp:39
#19 0x08a4b2ac in Boolean2Test::queriesTest (this=0x9b794c8, queryText=L"+w3 +xx", expDocNrs=...) at /lucene++-3.0.7/src/test/search/Boolean2Test.cpp:118
#20 0x08a47704 in Boolean2Test_testQueries01_Test::TestBody (this=0x9b794c8) at /lucene++-3.0.7/src/test/search/Boolean2Test.cpp:164
#21 0x08b36869 in HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x8cd625d "the test body", method=&virtual table offset 16, this adjustment 163026120, object=<optimized out>)
    at /lucene++-3.0.7/src/test/gtest/src/gtest.cc:2077
#22 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x9b794c8, method=<optimized out>, location=0x8cd625d "the test body") at /lucene++-3.0.7/src/test/gtest/src/gtest.cc:2113
#23 0x08b2c8c9 in testing::Test::Run (this=0x9b794c8) at /lucene++-3.0.7/src/test/gtest/src/gtest.cc:2150
#24 0x08b2ca24 in testing::TestInfo::Run (this=0x8f561f8) at /lucene++-3.0.7/src/test/gtest/src/gtest.cc:2325
#25 0x08b2cb15 in testing::TestCase::Run (this=0x8f56280) at /lucene++-3.0.7/src/test/gtest/src/gtest.cc:2443
#26 0x08b2ce1e in testing::internal::UnitTestImpl::RunAllTests (this=0x8f0a020) at /lucene++-3.0.7/src/test/gtest/src/gtest.cc:4306
#27 0x08b36db9 in HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x8cd7594 "auxiliary test code (environments or event listeners)", 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x8b2cbb0 <testing::internal::UnitTestImpl::RunAllTests()>, this adjustment 149987360, object=<optimized out>)
    at /lucene++-3.0.7/src/test/gtest/src/gtest.cc:2077
#28 testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x8f0a020, method=<optimized out>, 
    location=0x8cd7594 "auxiliary test code (environments or event listeners)") at /lucene++-3.0.7/src/test/gtest/src/gtest.cc:2113
#29 0x08b2d131 in testing::UnitTest::Run (this=0x8f00720 <testing::UnitTest::GetInstance()::instance>) at /lucene++-3.0.7/src/test/gtest/src/gtest.cc:3927
#30 0x08411feb in RUN_ALL_TESTS () at /lucene++-3.0.7/src/test/gtest/include/gtest/gtest.h:2304
#31 main (argc=1, argv=0xffffd954) at /lucene++-3.0.7/src/test/main/main.cpp:68

**Comment by LocutusOfBorg** [comment]
and the same failure is on hurd-i386
